name: Deploy Continuo

on:
  push:
    branches:
      - main   # Se activa al hacer push a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js (ejemplo para apps Node)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: Construir aplicación
        run: npm run build

      - name: Desplegar en servidor (ejemplo con SSH)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/tu-app
            git pull origin main
            npm install --production
            pm2 restart app
